version: '2'
services:
  bootstrap:
    build: bootnode
    restart: on-failure
    container_name: bootstrap
    hostname: bootstrap
    entrypoint: /root/start.sh
    command: '--datadir=~/.ethereum/devchain --cache 2048 --lightkdf --gcmode archive --allow-insecure-unlock --rpcapi "db,personal,eth,net,web3" --rpccorsdomain="*" --networkid=54766 --rpc --rpcvhosts="*" --rpcaddr="0.0.0.0" --mine --password /root/files/password/password --unlock 0xf5322a7d899399419f949de6814c37255a2781df'
    volumes:
      - ./files/password:/root/files/password:ro
      - ./files/genesis.json:/root/files/genesis.json:ro
      - /etc/localtime:/etc/localtime:ro
      - ~/.ethereum/devchain:/root/.ethereum/devchain:rw
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
  eth:
    build: geth-client
    restart: on-failure
    links:
      - bootstrap
    entrypoint: /root/start.sh
    volumes:
      - ./files/password:/root/files/password:ro
      - ./files/genesis.json:/root/files/genesis.json:ro
      - /etc/localtime:/etc/localtime:ro
    command: '--datadir=~/.ethereum/devchain --allow-insecure-unlock --rpccorsdomain="*" --networkid=54766 --rpc --bootnodes="enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@XXX:30303" --password /root/files/password/password --unlock 0'

  etherchain-light:
    build: etherchain-light
    container_name: explorer
    restart: on-failure
    links:
      - bootstrap
    volumes:
      - ./etherchain-light:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 80:3000
