version: '2'
services:
  bootstrap:
    image: chtboot
    restart: on-failure
    container_name: bootstrap
    hostname: bootstrap
    entrypoint: /root/start.sh
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
  eth:
    image: chtnode
    restart: on-failure
    links:
      - bootstrap

  eth2:
    image: chtnode
    restart: on-failure
    links:
      - bootstrap

  eth3:
    image: chtnode
    restart: on-failure
    links:
      - bootstrap
  eth4:
    image: chtnode
    restart: on-failure
    links:
      - bootstrap
