version: '3'
services:
  bootstrap:
    image: chttl.azurecr.io/chtboot
    restart: on-failure
    container_name: bootstrap
    hostname: bootstrap
    entrypoint: /root/start.sh
    ports:
      - "80:8545"
  eth:
    image: chttl.azurecr.io/chtnode
    restart: on-failure
  eth2:
    image: chttl.azurecr.io/chtnode
    restart: on-failure
  eth3:
    image: chttl.azurecr.io/chtnode
    restart: on-failure
  eth4:
    image: chttl.azurecr.io/chtnode
    restart: on-failure

